# Generated by Django 4.1.3 on 2022-11-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.template.context_processors


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_created=True)),
                ('product_name', models.CharField(max_length=70)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('place', models.CharField(max_length=70)),
                ('brand_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to=django.template.context_processors.media)),
                ('Receipt_image', models.ImageField(null=True, upload_to=django.template.context_processors.media)),
                ('Uzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Userz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
