# Generated by Django 4.1.3 on 2022-11-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
