# Generated by Django 4.1.3 on 2022-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('place', models.CharField(max_length=70)),
                ('brand_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to=None)),
                ('Receipt_image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pasword',
        ),
    ]
