# Generated by Django 4.1.3 on 2022-11-20 12:02

from django.db import migrations, models
import django.template.context_processors


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_collector_userz_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='product_image',
            field=models.ImageField(null=True, upload_to=django.template.context_processors.media),
        ),
    ]
